### ISSUE TITLE
Carpe windows build

### ISSUE THREAD

**Issue by simsekgokhan** [0LNetworkCommunity/carpe#1]
### Steps to build on Windows 10:

- Change carpe tauri toml to use this branch: https://github.com/OLSF/libra/tree/carpe-build  
- Note: Building on Win 7 is not supported (due to NodeJS version 16 req.)
- Make sure you have done this: https://tauri.studio/en/docs/getting-started/setup-windows
- Build gmp statically: 1. Install vcpkg: https://github.com/microsoft/vcpkg#getting-started, 2. Build/install gmp: `vcpkg install gmp:x64-windows-static`

### Next actions:
- [ ] Use file redirection for `sdk/transaction-builder/src/stdlib.rs`, `sdk/client/src/proxy.rs` in https://github.com/OLSF/libra/commit/fda2d71687cb1af4dc1732287c911a89935bd495
      Hint: Try this: https://stackoverflow.com/questions/5917249/git-symlinks-in-windows
- [ ] Find cross-platform package/fix or add conditional compiling and windows implementation for these commented sections `ol/cli/src/node/node.rs` `ol/cli/src/mgmt/management.rs` in https://github.com/OLSF/libra/commit/fda2d71687cb1af4dc1732287c911a89935bd495

**Comment by simsekgokhan** [comment]
@0o-de-lally @liangping FYI.

**Comment by 0o-de-lally** [comment]
deprecated
