### ISSUE TITLE
Balance keeps decreasing as I mine

### ISSUE THREAD

**Issue by WyattLiu** [0LNetworkCommunity/carpe#10]
I am very new to this, may I ask if when would I be able to increase my balance after iterations of mining?

Right now I have done a few iterations but my balance decreased to 977k-ish.
TOWER HEIGHT	LAST EPOCH MINED	PROOFS THIS EPOCH	
12	19	13

Hope I am not the only guy lost. Thank you in advance.

**Comment by 0o-de-lally** [comment]
@WyattLiu Balance decreases because you are sending transactions to network. Everyday at 16:00 UTC the network sends out the coins from previous day mining.

Why don't you drop into the Discord.  I think you're in a very alpha build https://discord.gg/AzCp63pggW

**Comment by WyattLiu** [comment]
Thank you for the invite. I am using carpe-0.0.1.3 windows installer edition to try it out on windows.
