### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by TheMainlander** [0LNetworkCommunity/carpe#132]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

**Print screen or Debug/Console error message**
```
Error (100): loadAccounts: misc error, message: "EOF while parsing a value at line 1 column 0
```

## Expected Behavior

Carpe should check the see, validate and activate with valid seed.

## System information

**Please complete the following information:**

Release
Version: v0.5.0

Branch:
Commit: f3235c5b

---

Edition	Windows 11 Home
Version	21H2
Installed on	‎1/‎12/‎2021
OS build	22000.832
Serial number	033966113657
Experience	Windows Feature Experience Pack 1000.22000.832.0

Processor	AMD Ryzen 5 Microsoft Surface (R) Edition   2.20 GHz
Installed RAM	16.0 GB (15.5 GB usable)

System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

## Additional context

I can't mine!

![image](https://user-images.githubusercontent.com/38913700/183245116-635eca45-3d15-492b-b0f5-e6e9e4949de5.png)

![image](https://user-images.githubusercontent.com/38913700/183245125-95c9bb59-2b2e-44a2-9c59-e10767e051e0.png)

![image](https://user-images.githubusercontent.com/38913700/183245137-980a8459-fd27-44c0-966e-3ca31678667d.png)

**Comment by TheMainlander** [comment]
Gah, I fixed it ... 
![image](https://user-images.githubusercontent.com/38913700/183245556-5340ab66-ca19-4cd1-af81-44d27f4110b8.png)

But getting the Seed button to not insta-disappear on restart ... mission but I got there!

**Comment by zaidbsousa** [comment]
How did u fix Error (100)?? I still get it

**Comment by 0o-de-lally** [comment]
Deprecated
