### ISSUE TITLE
[Bug] Carpe does not show account balance

### ISSUE THREAD

**Issue by kalvkusk** [0LNetworkCommunity/carpe#175]
# 🐛 Bug

Carpe 1.0.0-16 is running on mac but balance is not showing and account is said to not be on chain (it is)

## To reproduce

**Steps to reproduce**
Install Carpe 
Start and check first screen.

**Print screen or Debug/Console error message**
```
Sample logfile output
```

## Expected Behavior

Show all accounts and their balances

## System information

**Please complete the following information:**
Carpe 1.0.0-16 
MacOS 14.2.1 M1 Pro CPU

## Additional context

Sample additional context

**Comment by chip2017** [comment]
carpe doesn't work. Latest version 17. I launch it, turn on the miner and that’s it, immediately a white background.
![Clipboard_01](https://github.com/0LNetworkCommunity/carpe/assets/42459646/cf0eb918-2d4d-4b6b-8588-5d67a12387ff)

**Comment by kalvkusk** [comment]
Closing sample bug report
