### ISSUE TITLE
carpe_1.0.0_x64-setup.exe give me empty window on windows 11

### ISSUE THREAD

**Issue by philobbe** [0LNetworkCommunity/carpe#182]
# 🐛 Bug

After install carpe_1.0.0_x64-setup.exe on my windows 11 64 bit I get empty windows

carpe.log contains only :

19:10:40 [WARN] Carpe starting

I had version 0.5 installed previously

- carpe_1.0.0_x64-setup.exe version 21/01/2024
- Windows 11 Professionel

![003059](https://github.com/0LNetworkCommunity/carpe/assets/25483500/ccbdaa1e-92eb-4d2c-97cf-8ae03fe1c7a8)

![003058](https://github.com/0LNetworkCommunity/carpe/assets/25483500/aa9a794e-2543-434c-af6b-09ea754345ab)

**Comment by philobbe** [comment]
I specify that I had disconnected my antivirus for the installation to be sure not to have a detection problem

**Comment by kalvkusk** [comment]
@philobbe try latest canary, this issue is resolved. 

[https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-17-canary](url)

**Comment by flux334455** [comment]
hi, same problem with regular 1.0.0 and 1.0.17 canary 
Firewall down
Antivirus down
Both app autorized in firewall 
only the 0.5.0 can run on my PC 

![image](https://github.com/0LNetworkCommunity/carpe/assets/73361043/f156ebe7-3307-42f2-b721-247352caab23)

**Comment by imashowman** [comment]
same problem!

**Comment by kalvkusk** [comment]
@imashowman https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-17-canary try canary please and report back

**Comment by imashowman** [comment]
> @imashowman https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-17-canary try canary please and report back

same issue...

**Comment by kalvkusk** [comment]
@imashowman alright, I will test few fixes in the evening. 

so its latest Win 11 with all official updates right?

**Comment by imashowman** [comment]
> @imashowman alright, I will test few fixes in the evening.
> 
> so its latest Win 11 with all official updates right?

yes

**Comment by imashowman** [comment]
> > @imashowman alright, I will test few fixes in the evening.
> > so its latest Win 11 with all official updates right?
> 
> yes



> @imashowman alright, I will test few fixes in the evening.
> 
> so its latest Win 11 with all official updates right?

same issue in 2 pcs, carpe 0.5 was running before i uninstalled

**Comment by kalvkusk** [comment]
![multiple_acc_carpe_qa](https://github.com/0LNetworkCommunity/carpe/assets/44435644/ee0cf388-2574-40dc-86a1-10ef2a00c470)
This is clean install win11, I'm not sure whats different with the machines You are running on

**Comment by imashowman** [comment]
dont know.. i only have this on carpe.log

![image](https://github.com/0LNetworkCommunity/carpe/assets/111128714/1233dda6-9850-46a8-9421-ece3be6ad1fe)

**Comment by kalvkusk** [comment]
@imashowman 
https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer
 try installing this and restart carpe.

**Comment by Teisson** [comment]
Hmm, yeal I'll try to see if I can figure out the bug for the windows build

**Comment by tena6ous** [comment]
I got the same issue, canary version does not work either.
- Windows 11 pro 23h2 (Windows Feature Experience Pack 1000.22681.1000.0) installed 2 months ago, tried windows compatibility mode for the executable, does not work
- Webview2 already installed on my machine, tried to repair installation, does not work
- Antivirus: Bitdefender Antivirus Plus, tried to make exception on the executable, does not work
- Tried computer restart after all of that, not working either

**Comment by Chantalsuisse** [comment]
I have the same issue : white screen after installing Carpe. 
I use Windows 365 with ASUS PC.
Here are my tests :
- MicrosoftEdgeWebview2Setup.exe was installed before and I could not reinstall it, Edge message said "Installation failed. Microsoft Edge Webview2 Runtime is already installed on the system."
- I tried installation with my VPN on Switzerland, then Singapore, then Montreal Canada, then Miami USA. Each time reinstalling.
- Then (still with VPN in USA) I uninstalled Capre entirely with Windows unistallation tools and I installed it again with version carpe_1.0.0_x64-setup.exe
- Then I uninstalled again and I installed again version carpe_1.0.0_x64_en-US.msi
...I had the white screen at Carpe opening during each of my tests.
In this white screen I have only 2 items in the menu : Carpe (only one choice : Exit) and Edit (4 choices : Cut Copy Paste SelectAll)
Many thanks in advance for your help :-)
![image](https://github.com/0LNetworkCommunity/carpe/assets/40007117/130a5e1e-6df9-4a7f-a5c8-30141feaf465)

**Comment by st-way** [comment]
This topic might help devs: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3191
Last message states the following: 
**We experience this issue as well. For us, we noticed it was happening whenever we were showing a MessageBox while the WebView2 was initializing. If we suppress the message box, it seems to start. Otherwise we get the blank view. If we kill and restart the web view, it starts working.**

**Comment by st-way** [comment]
Some updates: a french user in Discord found out that changing the default locale to English fixed the blank display issue. Could you try to set the locale to English?

**Comment by C0wnuts** [comment]
Changing the default locale to English (United States) worked for me ! 

**Changing the locale to English (US) works on both MacOS and Windows to fix the white/empty window bug!**

**-- Windows steps --**
**Step to quick fix while awaiting a possible patch :** 
1. Go to parameters
2. "Heure et langue" / "Time and language" (or something like this)
3. "Langue et région" / "Language and area" (or something like this)
4. On : "Langues préférées" / "Preferred language" -> click on : "Ajouter une langue" / "Add language"
5. Select English (United States) -> "Suivant" / "Next" -> tick all optional language features -> install
6. Wait until the pack is installed
7.  Back to "Heure et langue" / "Time and language" - "Langue et région" / "Language and area" -> on "Langue d'affichage de Windows" / "Windows display language" -> select English (United States)
8. Log out -> Log in again (If that's not enough, reboot)
9. Open CARPE again and voilà ! 

![Capture d'écran 2024-02-12 112530](https://github.com/0LNetworkCommunity/carpe/assets/22750213/d6d25132-fa11-48d0-8b91-738b52202b9b)

**!!** Keyboard is now in qwerty so you can quickly change your keyboard layout by hitting **alt** + **shift** or in the bottom right-hand corner of the task bar, change the language by clicking on "ENG" and change to "FRA" (or your language if different from FRA) **!!**

**!!** Your default language may now be "English (United States) when you start your PC. Don't panic, go back to Settings -> "Time and language" - "Language and area" drag your language above English in the section just below "Preferred languages" and change "Windows display language" back to French (or your language). Reboot **!!**

**-- MacOS steps --**
**Step to quick fix while awaiting a possible patch :**

Change the OS locale to English US.
I don't have a MAC so I can't detail the procedure. If anyone feels like detailing the procedure for MACs, go ahead. ;)

**Comment by kalvkusk** [comment]
I love the engagement. We will scramble asap to fix this :)

**Comment by tena6ous** [comment]
> Some updates: a french user in Discord found out that changing the default locale to English fixed the blank display issue. Could you try to set the locale to English?

French locale here too. Switched to English/US locale and it's working like a charm.
Thanks @C0wnuts too for the full details!

**Comment by Teisson** [comment]
Alright guys, we've located the issue and written a function to override the i18n pack, causing the white screen and hanging parts of the wallet. Can you guys please download the latest version here:

https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-18-canary 

Import your wallet, update the playlist and restart the app. I've stress tested the wallet in windows 11 and we have had good feedback from windows 10 as well as Mac OS users. If I hear nothing further I will assume we're good and close your ticket =)

**Comment by kalvkusk** [comment]
Closing as issue is pin pointed
