### ISSUE TITLE
[Bug]Blank window

### ISSUE THREAD

**Issue by 77ZZ77** [0LNetworkCommunity/carpe#183]
# 🐛 Bug

I installed carpe_1.0.0_x64.dmg on MacBook Air M1 2020 (Ventura 13.3.1) and after starting carpe it shows a blank white window / screen.

An old version of carpe was running on this laptop before.

## To reproduce
Install and start carpe.

**Print screen or Debug/Console error message**

<img width="749" alt="x Bildschirmfoto 2024-01-21 um 20 35 09" src="https://github.com/0LNetworkCommunity/carpe/assets/157315450/5fb31753-fd21-4474-8a22-83d37fe8e201">

// Paste the output here
```

## Expected Behavior

<!-- A clear and concise description of what you expected to happen. -->

## System information

**Please complete the following information:**
- <!-- Carpe Version -->
- <!-- Computer OS -->

## Additional context

Add any other context about the problem here.

**Comment by BBK8530** [comment]
@77ZZ77 
Thanks for the feedback, can you provide the carpe.log file?
The file should be located at : /Users/{userName}/Library/Application Support/com.carpe.carpe/carpe.log

**Comment by kalvkusk** [comment]
Closing. No feedback for 3 weeks.
