### ISSUE TITLE
[Bug] - Missing dlls on windows 11 Home

### ISSUE THREAD

**Issue by The1OneID** [0LNetworkCommunity/carpe#186]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

1. Install [carpe](https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0) on a vanilla windows 11 Home.
2. Run carpe. Notice that it complains about at least 2 missing dll, please find below a screenshot of one of them.

**Print screen or Debug/Console error message**

<img width="491" alt="Screenshot 2024-01-21 at 22 06 24" src="https://github.com/0LNetworkCommunity/carpe/assets/109752379/d13483a6-f0c6-41ef-92b6-7ca5c4144e58">

## Expected Behavior

<img width="993" alt="Screenshot 2024-01-21 at 22 35 16" src="https://github.com/0LNetworkCommunity/carpe/assets/109752379/1e874220-38e3-42c4-866f-3a91c0e39c85">

## System information

**Please complete the following information:**
Carpe v1.0.0
Windows 11 Home, version 23H2

## Additional context

I was able to fix installing Visual C++ 2015-2022

**Comment by kalvkusk** [comment]
https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-17-canary try this and report back.

**Comment by kalvkusk** [comment]
@The1OneID fixed. Closing
