### ISSUE TITLE
[Bug] Blank results in Carpe (last account in list, slow wallet, click Miner)

### ISSUE THREAD

**Issue by sirouk** [0LNetworkCommunity/carpe#188]
# 🐛 Bug

The MINER tab is showing blank screen and then the other menu items stop working.

I can CTRL + SHIFT + R to refresh and get things working again without having to quit the program.

## To reproduce:
Install Carpe Canary via https://github.com/0LNetworkCommunity/carpe/releases/tag/v1.0.0-17-canary and opt to uninstall and keep data. Then have a handful of accounts, click around and toggle them, then pick the last one, then click MINER.

It's a slow wallet, so I'm not sure if that might have anything to do with it.

## Here's what it looks like:
https://i.imgur.com/Mb4g2vx.png

## Expected Behavior
I expected to see the miner screen and to continue being able to use the app.

## System information
- Release v1.0.0-17-canary
- Windows 11

**Comment by kalvkusk** [comment]
@sirouk please test the v1.0.0-18-canary and report back

**Comment by sirouk** [comment]
> @sirouk please test the v1.0.0-18-canary and report back

Will do!

**Comment by sirouk** [comment]
@kalvkusk works flawlessly 🙏 thanks!
