### ISSUE TITLE
[Bug] Blank screen on MacOS Sonoma

### ISSUE THREAD

**Issue by denzeldumfrieswashington** [0LNetworkCommunity/carpe#189]
# 🐛 Bug

Blank screen when opening Carpe, nothing is shown on screen.

## To reproduce

Install Carpe on MacOS and open it.

## System information

- Carpe v1.0.0 and v1.0.0-17-canary
- MacOS Sonoma 14.2.1 and 14.3

## What it looks like

![Image 22-01-2024 à 09 28](https://github.com/0LNetworkCommunity/carpe/assets/157538391/3d1fdc72-f410-43f2-b6ac-7c7ce217b039)

**Comment by vandrieu** [comment]
same here

**Comment by kalvkusk** [comment]
Fixed.
