### ISSUE TITLE
[Bug]After clicking the top three buttons multiple times, the page gets stuck.

### ISSUE THREAD

**Issue by JackLamCHN** [0LNetworkCommunity/carpe#190]
Carpe Version：v1.0.0-17-canary
Systems：Windows10
[Bug]After clicking the top three buttons multiple times, the page gets stuck. Unable to click, unable to switch interfaces, unable to open the settings menu interface.
![image](https://github.com/0LNetworkCommunity/carpe/assets/35221070/6fbff7ae-209c-499a-ae22-d757ba799b2e)

**Comment by kalvkusk** [comment]
@JackLamCHN please try 1.0.0-18-Canary version and report back

**Comment by kalvkusk** [comment]
Fixed
