### ISSUE TITLE
[Bug]Unable to submit proof, unable to mine.

### ISSUE THREAD

**Issue by JackLamCHN** [0LNetworkCommunity/carpe#191]
Version：v1.0.0-17-canary
Systems：Windows10
Carpe is unable to submit proofs. The first time I installed it, I could submit two proofs, but later the interface got stuck. After restarting, it has been stuck at 0%, and mining is not possible.

![image](https://github.com/0LNetworkCommunity/carpe/assets/35221070/d0fe4694-e03e-4bbb-84d4-a241a53a9111)

Carpe.log
![image](https://github.com/0LNetworkCommunity/carpe/assets/35221070/9c2c4736-c7ec-4c12-8a7c-83f1eb463785)

**Comment by arif48** [comment]
me to

**Comment by kalvkusk** [comment]
please try 1.0.0-18-Canary version and report back

**Comment by kalvkusk** [comment]
Fixed
