### ISSUE TITLE
[Bug] Users who submitted 72 proofs in the last epoch before the v6.9 upgrade, and used the new version of carpe after the upgrade, could not submit new proofs, prompting that 72 had already been submitted

### ISSUE THREAD

**Issue by BBK8530** [0LNetworkCommunity/carpe#194]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

**Print screen or Debug/Console error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
-

**Comment by kalvkusk** [comment]
This is not a bug, thats by design. A single user can submit only 72 proofs per epoch.

**Comment by kalvkusk** [comment]
Mining is sunsetted.
