### ISSUE TITLE
I cannot dowload the wallet please help [Bug]

### ISSUE THREAD

**Issue by SamKa77** [0LNetworkCommunity/carpe#197]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

**Print screen or Debug/Console error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
-

**Comment by SamKa77** [comment]
I'm on IOS

**Comment by kalvkusk** [comment]
@SamKa77 for IOS try Oollet. Carpe is for Windows, MacOS
