### ISSUE TITLE
[Bug] Info and resolution for white screen

### ISSUE THREAD

**Issue by Ziltosh** [0LNetworkCommunity/carpe#198]
# 🐛 Bug

Here are the details I've found and what I've done to fix the white screen issue locally when the language is not set to English.

## To reproduce

**Steps to reproduce**
Install Carpe on non english system/brower.

**Print screen or Debug/Console error message**
```
[HMR][Svelte]"Unrecoverable HMR error in <AccountSwitcher>: next update will trigger a full reload"
Error: [svelte-i18n] Cannot format a message without first setting the initial locale.
```

## System information

**Please complete the following information:**
- Carpe 1.0.0
- MacOS 14 Sonoma

## Change

In src/lang/i18n.ts
Add is_loading in import and export
import { locale, init, _, getLocaleFromNavigator, register, isLoading } from 'svelte-i18n'
...
export { _, setupI18n, getLocaleFromNavigator, locale, isLoading }

---

In AccountSwitcher.svelte
Wrap the dropdown with {#if !isLoading} after import it.

**Comment by kalvkusk** [comment]
@BBK912

**Comment by kalvkusk** [comment]
Thank You for debugging this @Ziltosh

**Comment by kalvkusk** [comment]
fixado
