### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cheolhojo** [0LNetworkCommunity/carpe#202]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

**Print screen or Debug/Console error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
- 

## Additional context

I don't see any sign of resolving this symptom Are you preparing for an update?

Doesn't ol give carpe miners a fair chance? Norders is still mining now, and this period seems to be about two months old. The longer the period, the more unequal the [structure](url)
![Screenshot_20240213-111953_Chrome](https://github.com/0LNetworkCommunity/carpe/assets/105683424/e19b6f19-3e79-4eb1-8830-7bba330756af)

![Screenshot_20240213-111928_Chrome](https://github.com/0LNetworkCommunity/carpe/assets/105683424/0534bdff-b5da-401e-b3c6-7775e1b2e5b4)

**Comment by kalvkusk** [comment]
please try 1.0.0-18-Canary version and report back
