### ISSUE TITLE
[Bug] Wallet doesn't load up in V1.0

### ISSUE THREAD

**Issue by 0xJiren** [0LNetworkCommunity/carpe#203]
I had Carpe v0.5 installed on my computer since June last year. After a while, today I decided to check my account and noticed that I cannot connect to 0L Network. 

![photo_6219619640183735664_y](https://github.com/0LNetworkCommunity/carpe/assets/159876928/76ae32a7-dd2a-4fa6-b413-fb6ac4d03899)

My mnemonic key which I written down is missed and I spoked to mod team for support. One of the mods (David) suggested to me install V1.0 in order to connect to the network overwriting the previous installation directory and the wallet should automatically load up. I installed it but the wallet was missing.

![img-ezgif com-webp-to-jpg-converter](https://github.com/0LNetworkCommunity/carpe/assets/159876928/cc5c254b-9d32-4853-97a6-fc8670708e9e)

I backed up my files on C:\Users\YOUR_USER/0L already and would require your support to recover the assets.

## System information

Carpe V1.0
Windows 11 Home OS Build 22631.3085

## Additional context

I also tried to recover the account using auth_key in accounts.json using recovery option but it doesn't work.

**Comment by Teisson** [comment]
I'll close the ticket. Glad you got your access back :)
