### ISSUE TITLE
NOT CONNECTED TO CHAIN, DATA MAY BE OUT OF SYNC

### ISSUE THREAD

**Issue by HubDis** [0LNetworkCommunity/carpe#206]
# 🐛 Bug

Hi I downloaded Carpe Canary 1,0.0.8. I have Win11.

Wallet not connect to the network. I requested to be onboard 1 day ago. 
There is and information: NOT CONNECTED TO CHAIN, DATA MAY BE OUT OF SYNC

- 
- 

![image](https://github.com/0LNetworkCommunity/carpe/assets/160008975/ec5d4c95-da19-4949-9d26-b2232cf7842c)
.

**Comment by Teisson** [comment]
Thank you for reaching out and glad we could help you resolve the issue!

**Comment by kalvkusk** [comment]
Issue resolved
