### ISSUE TITLE
Carpe was stuck on 94% on first proof and now just blank page

### ISSUE THREAD

**Issue by AirdropOstrich** [0LNetworkCommunity/carpe#207]
**Carpe version:** carpe-canary_1.0.0.18_x64_en-US.msi
**System:** Windows 10 Home i5 Intel with Nvidia and 16 gb ram

**Description:** 
So, I downloaded the carpe and received my 1 coin to onboard on the chain.
I started mining the first block, but it stuck at 94%. I left my laptop on for 24 hours and still was 94%. So I asked Discord support and they told me to restart and click on debug etc. But it is not getting fixed and I don't think I mined the first proof either.

Now, all I can see is a white screen on the mining page.
Also once you click on the mining page, you cannot click anywhere else or go to another tab until you exit the app and start it again.

I am posting here because I was told to seek help here on github.
So, I'd appreciate if anybody can help me. I am very eager to mine my first proof, but that probably got voided cos I closed at 94% after 25 hours :(

Let me know,
below screenshots of error log and screen pages.

<img width="1078" alt="Screenshot 2024-02-14 at 09 22 26" src="https://github.com/0LNetworkCommunity/carpe/assets/160009301/5b259f29-5719-4d32-a680-7c31c3d1fca3">
<img width="1124" alt="Screenshot 2024-02-14 at 09 24 01" src="https://github.com/0LNetworkCommunity/carpe/assets/160009301/e19f6a2a-3d19-4b75-84a2-763ae10bf382">

<img width="1078" alt="Screenshot 2024-02-14 at 07 36 13" src="https://github.com/0LNetworkCommunity/carpe/assets/160009301/87e069fb-76b9-48ad-a306-4b1c5b15bdce">

**Comment by kalvkusk** [comment]
Mining is sunsetted.
