### ISSUE TITLE
Error: could not compile diem-node

### ISSUE THREAD

**Issue by TK1428** [0LNetworkCommunity/carpe#21]
Any idea what happened here after `make bins install` ?
<img width="1165" alt="Bildschirmfoto 2021-11-18 um 16 20 34" src="https://user-images.githubusercontent.com/47744267/142447339-3b339215-c0c3-4628-832f-c2dba0478fce.png">
<img width="819" alt="Bildschirmfoto 2021-11-18 um 16 00 16" src="https://user-images.githubusercontent.com/47744267/142441392-539c60fb-c82c-42eb-8269-e9c0408db635.png">
<img width="1168" alt="Bildschirmfoto 2021-11-18 um 16 13 07" src="https://user-images.githubusercontent.com/47744267/142442409-692fce9b-17ff-4cb1-905b-1ad8e3428604.png">

**Comment by soaresa** [comment]
Please reach out our help-desk channel for that. 
https://discord.com/channels/833074824447655976/846447504047341578
