### ISSUE TITLE
[Bug] Application crashed.

### ISSUE THREAD

**Issue by MacksVersion** [0LNetworkCommunity/carpe#210]
# 🐛 Bug

It went up to 40% mining and then it crashed and nothing worked... I restarted it and now it works fine until I click on mining... then the app crashes and nothing else works.

**Print screen or Debug/Console error message**
```

https://github.com/0LNetworkCommunity/carpe/assets/107284806/c51c53f6-4f6d-49b2-84ca-e7dbce55d87b


```
![Captura de tela 2024-02-15 191011](https://github.com/0LNetworkCommunity/carpe/assets/107284806/05cf9289-e80b-481b-8f92-9283f5a5affa)

## System information

**Please complete the following information:**
- 
canary_1.0.0-18_x64-setup.exe
- 
Windown 11

**Comment by BBK8530** [comment]
@kalvkusk Please assign this to me.

**Comment by MacksVersion** [comment]
Do you need any more information? What should I do?

**Comment by MacksVersion** [comment]
To complement, I made a new account from scratch on my laptop, it stuck at 101% and it was the same as this account that stuck at 40%

**Comment by BBK8530** [comment]
> To complement, I made a new account from scratch on my laptop, it stuck at 101% and it was the same as this account that stuck at 40%

We'll troubleshoot the problem.

**Comment by MacksVersion** [comment]
@BBK912 I did the update and the error persists... after using my seed phrase and starting mining again it crashes again,

**Comment by MacksVersion** [comment]
![Uploading Captura de tela 2024-02-18 165230.png…]()

**Comment by MacksVersion** [comment]
![Captura de tela 2024-02-18 165230](https://github.com/0LNetworkCommunity/carpe/assets/107284806/6652ae7f-3d94-4098-af7e-df1af9836b00)

**Comment by MacksVersion** [comment]
![Captura de tela 2024-02-18 165458](https://github.com/0LNetworkCommunity/carpe/assets/107284806/729db507-985a-4021-b908-6aece9ad9e32)

LOGS
ERRORS 
Error ID: 404
Message: getTowerChainView: Transaction Error: AbortCode: Some(State { chain_id: 1, epoch: 55, version: 23936714, timestamp_usecs: 1708286014135371, oldest_ledger_version: 0, oldest_block_height: 0, block_height: 11902398, cursor: None }), Message: DiemError { message: "Resource not found by Address(0x7e0189a11e1d21246eba65d8ff3226804a0fec6f52a3dff9863c64a3b760488c), Struct tag(0x1::tower_state::TowerProofHistory) and Ledger version(23936714)", error_code: ResourceNotFound, vm_error_code: None }
LATEST REQUEST
true

CLIENT STATE

is init: true
is connected: true
is refreshing: false
signing account: { "account": "7e0189a11e1d21246eba65d8ff3226804a0fec6f52a3dff9863c64a3b760488c", "auth_key": "0x7e0189a11e1d21246eba65d8ff3226804a0fec6f52a3dff9863c64a3b760488c", "nickname": "7e0", "on_chain": true, "balance": { "unlocked": 1000000, "total": 1000000 }, "locale": "en" }
is onchain: true
can migrate: false
is account refreshed: true
all accounts: [ { "account": "7e0189a11e1d21246eba65d8ff3226804a0fec6f52a3dff9863c64a3b760488c", "auth_key": "0x7e0189a11e1d21246eba65d8ff3226804a0fec6f52a3dff9863c64a3b760488c", "nickname": "7e0", "on_chain": true, "balance": { "unlocked": 1000000, "total": 1000000 }, "locale": "en" } ]

**Comment by MacksVersion** [comment]
can you please help me?

**Comment by ghost** [comment]
@BBK912 see https://github.com/0LNetworkCommunity/carpe/issues/224
