### ISSUE TITLE
[Bug]WHITE SCREEN mining doesnt work just freez

### ISSUE THREAD

**Issue by MUERTE72** [0LNetworkCommunity/carpe#213]
# 🐛 Bug
![Zrzut ekranu 2024-02-16 181041](https://github.com/0LNetworkCommunity/carpe/assets/105079899/68b4d9a3-042f-49ba-a425-7ef64a9e6f51)

## To reproduce

**Steps to reproduce**

**Print screen or Debug/Console error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
canary_1.0.0-18_x64-setup.exe
WINDOWS 11
![11](https://github.com/0LNetworkCommunity/carpe/assets/105079899/87b6935b-0db9-4ac0-9dc9-a875f2b3b6d8)

**Comment by ghost** [comment]
See https://github.com/0LNetworkCommunity/carpe/issues/224
