### ISSUE TITLE
[Bug] Adding new account whilst mining is active

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#219]
# 🐛 Bug

If mining is active and user adds a new account, carpe will switch to and attempt mining with the new account. The miner page is then rendered without buttons etc, forcing users to restart carpe to turn off mining and be able to switch accounts.

Carpe: v1.0.1
OS: macOS Sonoma 14.3.1

![wallet](https://github.com/0LNetworkCommunity/carpe/assets/88262815/56e9872f-7c56-4356-b7bf-9b99bcde5320)
![miner](https://github.com/0LNetworkCommunity/carpe/assets/88262815/5ee2dd93-c74f-4866-b228-0bcd7d38cf8f)

**Comment by kalvkusk** [comment]
Fixado by @BBK912
