### ISSUE TITLE
[Bug] Error screen persists if user denies keyring password prompt when toggling miner on

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#221]
# 🐛 Bug

If user denies keyring password prompt when attempting to toggle miner on, error screen persists atop until restart.

Carpe: v1.0.1
OS: macOS Sonoma 14.3.1

![sticky-error](https://github.com/0LNetworkCommunity/carpe/assets/88262815/0c2f377f-42d3-4a33-99e3-90d9eb99b965)

**Comment by kalvkusk** [comment]
Mining is sunsetted.
