### ISSUE TITLE
[Bug] Proof accumulation after 72 proofs submitted in epoch

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#222]
# 🐛 Bug

Carpe: v1.0.1

It's my understanding that each proof is now tied to an epoch state and "fits" only that specific epoch, one can no longer "accumulate" proofs post 72 per epoch to submit in the next epoch. Messaging does not reflect this in carpe.

![proof-generation](https://github.com/0LNetworkCommunity/carpe/assets/88262815/4bb7b852-8704-485c-bbc1-c022ff457ff5)

In this scenario whilst the miner remains toggled on it looks to result in heavily repeated error logging too.

![log-be-eating](https://github.com/0LNetworkCommunity/carpe/assets/88262815/a4024028-f698-4459-b02d-ed832afa42a4)

An automatic toggle off for mining (with notification of this action) could be helpful, along with automatic enablement once a new epoch starts; although with mining to be deprecated soon perhaps just a cleanup of wording and error suppression befits?

**Comment by ghost** [comment]
I had to manually resubmit local proofs today after the epoch resumption, the above errors persisted until I did so.

**Comment by kalvkusk** [comment]
Mining is sunsetted.
