### ISSUE TITLE
[Bug]Loop installation

### ISSUE THREAD

**Issue by C-miuc** [0LNetworkCommunity/carpe#223]
# 🐛 Bug

## To reproduce

**Steps to reproduce**

The installation of CARPE repeats itself infinitely. I installed the app 2 days ago. But today when launching the application, an update of CARPE was requested. by accepting or refusing, the carp installation restarted in a loop
**Print screen or Debug/Console error message**
```
// Paste the output here
```

## System information

**Please complete the following information:**
- 
-

**Comment by kalvkusk** [comment]
Issue was: If carpe was installed with exe installer, then it would download msi updater and restart the the old version producing a loop. Fixed.
