### ISSUE TITLE
[Bug] Crash attempting to submit genesis proof

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#224]
# 🐛 Bug

v1.0.0/1 and Canary

Some users are reporting the miner crashes before being able to mine their genesis proof. Relaunching carpe and attempting to visit the miner tab then results in carpe crashing again. Note, users have been onboarded with 1 coin.

I can see proof_0.json has been created. I think there maybe something wrong with tx logic in this scenario as when I attempt to submit backlog I get an insufficient gas error, this is simply resolved by sending the address more coins.

1. After crash and proof_0.json exists relaunch carpe
2. Enable developers
3. Click submit backlog - fails due to insufficient gas
4. Deposit additional coins (10 coins used in my test)
6. Click submit backlog - success
7. Restart carpe
8. Miner tab can now be accessed without crashing
9. Miner produces and submits proof_1.json successfully

**Comment by BBK8530** [comment]
@siliconbits Thanks for such detailed feedback, it's really great
