### ISSUE TITLE
[Bug] Cannot start miner or transfer coins after creating or restoring account

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#225]
# 🐛 Bug

Carpe v1.0.1
OS: Windows 11 / macOS Sonoma 14.3.1

After creating or restoring an account (and being onboarded) users are unable to start the miner or transfer coins from the account. The wallet tab reflects the onboarded account balances immediately 👍 however both the miner and transfer tabs show the account as not existing on chain yet. This is not solved by clicking use playlist but it does resolve upon simply restarting carpe.

**Comment by BBK912** [comment]
#219

**Comment by kalvkusk** [comment]
Mining is sunsetted.
