### ISSUE TITLE
[Bug] broken link and image at Carpe download page

### ISSUE THREAD

**Issue by marciob** [0LNetworkCommunity/carpe#245]
# 🐛 Bug

Carpe download page doesn't show a download link at the "download" section ( https://0l.network/technology/carpe-desktop-app/ ). The user needs to visit the another link present there which also redirects to github where he/she can see the download link.

<img width="325" alt="image" src="https://github.com/0LNetworkCommunity/carpe/assets/13090422/abdc135b-154c-4ef3-b671-8e0cf78d69db">

but the correct download section link/image should be fixed.

**Comment by kalvkusk** [comment]
Fixed
