### ISSUE TITLE
[Bug] User can't got back to wallet view after accessing settings

### ISSUE THREAD

**Issue by soaresa** [0LNetworkCommunity/carpe#27]
# 🐛 Bug

## To reproduce

**Steps to reproduce**
Select an account out of the chain.
Go to settings.
Try to go back to Wallet view

**Print screen or Debug/Console error message**
![image](https://user-images.githubusercontent.com/10797037/142553052-30ed7a72-d54a-4667-a2cc-dddb71f3c7cc.png)

## Expected Behavior
Place a back button so user can return to the previous page.
![image](https://user-images.githubusercontent.com/10797037/142553115-57f7f596-b177-4fe5-a17b-34cfb59f1e01.png)

## System information

**Please complete the following information:**
- carpe-0.0.1.5-patch4
- All

**Comment by soaresa** [comment]
Fixed on [v0.1.0](https://github.com/OLSF/carpe/releases/tag/v0.1.0)

**Comment by 0o-de-lally** [comment]
deprecated
