### ISSUE TITLE
[Bug] Creating an additional account displays existing account address if miner is active

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#271]
# 🐛 Bug

When miner is active if user attempts to create an additional account the mnemonic generation screen displays the existing account address (that which is mining), rather than the new address derived from the mnemonic (this works as expected when mining is off). Clicking the generate different keys button results in the mnemonic changing however the account address still remains the same in this scenario. 

Note, the new account is properly created upon clicking create and displays correctly in accounts list regardless.

**Comment by kalvkusk** [comment]
Mining is sunsetted.
