### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by tioofoot** [0LNetworkCommunity/carpe#277]
I started with version 1.0.3 (on Win 11) by trying the mining function. Since then, I have accumulated 140 mining proofs without having sent and validated them on the chain.
Each time, carp tries to send the evidence but nothing happens...
Is this a known problem?
How do I validate my evidence before V7 and miner removal?
Thanks in advance

**Comment by BBK8530** [comment]
@tioofoot Are you in DC, where asking for help gets you a faster response?

**Comment by kalvkusk** [comment]
Mining is sunsetted.
