### ISSUE TITLE
[Bug] Carpe repeatably attempts to submit proofs when VM returns OutOfGas

### ISSUE THREAD

**Issue by ghost** [0LNetworkCommunity/carpe#279]
# 🐛 Bug

Miner attempted to submit a proof repeatably (every 30 seconds) for several hours whilst VM status returned out of gas each time, resulting in 800+ failed txs and ~250 coins spent on doing so (maximum gas was configured at 3000).

Suggestion would be if VM returns out of gas to halt backlog and inform user to check their gas settings rather than attempting further txs.

`
Error ID: 100
Message: listen(backlog-error): misc error, message: "Unknown error Transaction committed on chain, but failed execution: OutOfGas"
`

**Comment by kalvkusk** [comment]
Mining is sunsetted.
