### ISSUE TITLE
Able to have full access of Watch only

### ISSUE THREAD

**Issue by heavysword1** [0LNetworkCommunity/carpe#286]
# 🐛 Bug

<On Windows version of Carpe 1.0.7 if you add a wallet as watch only, and that wallet was originally created on that same machine you will have full access to the account, including transfer and changing wallet to slow. I did try with an account created on a different machine and was not able to have any functionality>

## To reproduce

Install Carpe 1.0.7
Add Watch account
Click transfer and boxes are not grayed out
Transfer will show success

Click Account control icon
Click Account actions
Set Slow Wallet will process

**Print screen or Debug/Console error message**
![image](https://github.com/0LNetworkCommunity/carpe/assets/96453474/5d637231-a726-4f32-91df-42639f6c9859)

```
// Paste the output here
```

## Expected Behavior

<I expected I should not be able to have access to a watch account, even if it was created by me>

## System information

**Please complete the following information:**

-  1.0.7
-  Windows

**Comment by kalvkusk** [comment]
@BBK912

**Comment by BBK8530** [comment]
@heavysword1  Can you try v1.0.8? It's not reproduced on my end.

**Comment by soaresa** [comment]
I just created a PR to prevent watch-only accounts from accessing the Transfer tab. Additionally, there was already a fix in place to prevent the "set slow wallet" action for watch-only accounts.

**Comment by soaresa** [comment]
@kalvkusk please close this issue.
