### ISSUE TITLE
[Feature Request] Fetch Waypoint, highlight button and add list of active peers

### ISSUE THREAD

**Issue by TheMainlander** [0LNetworkCommunity/carpe#29]
# 🚀 Feature Request

As a new Miner
I Want to onboard to Carpe and I may not know that I need to update my Peer/"URL of upstream node" by selecting the "Fetch Waypoint
So That my Peer address is correct and connected

AC1 - Peer not connected

Given I am a new Miner and my Peer is not connected (N)
When the connection fails the Fetch Waypoint button and URL will provide an error warning and highlight in red
Then the error will provide information to update the Peer and select "Fetch Waypoint" after updating

AC2 - List of active peers

Given I am a new/existing Miner and my  Peer/"URL of upstream node" has failed and is in error
When the error is presented 
Then a list of available Peers to select from will be available that are connected (Y) 
And Then I will be able to select an active connection

AC3 - Set new waypoint and update status to green/connected

Given I have selected an active Peer/"URL of upstream node"
When the system sets the  Peer/"URL of upstream node"
Then I will see the peer (Y) in green and can select the "Fetch Waypoint" to set the connection

## Motivation

**Is your feature request related to a problem? Please describe.**
New/existing Miners don't have a list of active peers and there's no status to advise of the peer being Up/Down, there's also no list of active peers to choose from

## Pitch

**Describe the solution you'd like**
Just an idea to improve the UI so the Miner knows the status and can then also select an active peer and then select "Fetch Waypoint" to update the peer.

**Describe alternatives you've considered**

None.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I'm not  a dev, soz,

## Additional context

![image](https://user-images.githubusercontent.com/38913700/142575021-4216ace3-1fa5-4739-bb4a-cdd161e87cc9.png)

**Comment by 0o-de-lally** [comment]
deprecated
