### ISSUE TITLE
[Feature Request] Build Carpe installers on Github Actions

### ISSUE THREAD

**Issue by soaresa** [0LNetworkCommunity/carpe#30]
# 🚀 Feature Request

## Motivation
Accelerate the process of publishing new releases.

## Pitch
Today it is only possible to build installers on a Mac OS.
Linux and Windows developers should be notified if building installers are failing asap.
Adding this task to GitHub Actions would be great!

- [x] Windows
- [x] Mac
- [ ] Ubuntu

**Comment by 0o-de-lally** [comment]
done on 1.0.0
