### ISSUE TITLE
[Feature Request] Confirmation / alert of setting Slow Wallet

### ISSUE THREAD

**Issue by nkrsic** [0LNetworkCommunity/carpe#31]
# 🚀 Feature Request

The background pages mention slow wallets. I clicked the button in Carpe (Windows) to set my wallet as a slow wallet. There was no error or confirmation, or any response that I noticed. So I'm not sure if it worked or not. Maybe there should also be some quick mouseovers to explain that slow wallets limits expenditure, etc. 

## Motivation

Not a problem, but a very-nice-to-have, helps with long holder adoption.

## Pitch

See above. A confirmation message / failure message in the Carpe Windows app. 

Time permitting, I can look at doing a PR. New to Svelte.

**Comment by TheMainlander** [comment]
In the documentation can we have a definition of what a "Slow Wallet" is versus a "Community Wallet" as well, please?

**Comment by 0o-de-lally** [comment]
Possibly deprecated. Please reopen if it is still an issue in 1.0.0
