### ISSUE TITLE
[CI] Carpe M1 build

### ISSUE THREAD

**Issue by rogerwalczak** [0LNetworkCommunity/carpe#32]
Package classgroup (libra repository) contains precompiled intel ar archive libgmp.a
Replacing it with M1 compiled libgmp.a (i.e. taken from brew gmp) makes Carpe compile and work as Apple executable

**Comment by soaresa** [comment]
Thanks @rogerwalczak !
@liangping , could you please take a look at this suggestion? Thanks!

**Comment by liangping** [comment]
Oh, Yeah, that's why it's failed on ubuntu as well. 
Thank you @rogerwalczak 
We used static compiling. we might have to change it back to dynamic.

**Comment by liangping** [comment]
@simsekgokhan Could you take a look, thank you

**Comment by o-mic-o** [comment]
Just thought I'd comment on this...In the meantime, it's possible to build carpe on M1 with:
```
cargo clean
cargo build --target=x86_64-apple-darwin
```

**Comment by 0o-de-lally** [comment]
current builds on 1.0.0 are universal. If you want optimized for M1 you'll need to build yourself from source
```
yarn install
yarn build
```
