### ISSUE TITLE
[Feature Request] Dynamically load list of possible upstream nodes

### ISSUE THREAD

**Issue by mortonbits** [0LNetworkCommunity/carpe#33]
# 🚀 Feature Request

## Motivation

As of now, one upstream IP address is configured in carpe binary. If this server fails, nearly all clients will also halt. Users have to go into discord and ask for support.

Next update of carpe plans to have a list of 3 peers in the shipped code. This is already a bit better.

## Pitch

Let's have a list of available full nodes e.g. in github.
This list should be read on carpe startup and used as input to select one upstream to connect to.

The advantage is, this list can be changed quickly (without release) if some new full nodes are added or it is known that some nodes will be down for longer time.

## Additional context

Related to https://github.com/OLSF/carpe/issues/29

**Comment by soaresa** [comment]
Added on [v0.1.0](https://github.com/OLSF/carpe/releases/tag/v0.1.0)
