### ISSUE TITLE
[Feature Request] Being able to select the location of ./0L directory 

### ISSUE THREAD

**Issue by frenzytejask98** [0LNetworkCommunity/carpe#36]
Currently, in Windows the ./0L directory is automatically built in C:/Users/admin(user)/ . While this may work well for Mac users as they usually have a single drive but a lot of Windows systems have a combination of partitions especially also because of the hybrid SSD (OS) and HDD (user data) architecture, there could be data management issues going further. Giving a choice of location while installation would be a nice to have feature!

**Comment by 0o-de-lally** [comment]
Deprecated. v1.0.0 uses platform's app folders
