### ISSUE TITLE
[Feature Request] implement Tauri auto updater

### ISSUE THREAD

**Issue by soaresa** [0LNetworkCommunity/carpe#38]
# 🚀 Feature Request

## Motivation

To keep users Carpe installs updated.

## Pitch

The best way to communicate Carpe users that there is a new release available to install is through Carpe itself.

We should open a modal when Carpe start telling user there is a new release available and/or keep a tag at some place (navbar or footer) telling a new version is available.

Carpe should also say if the user install is the latest.

If Carpe fails to connect to GitHub it must fail silently and tell it wasn't able to check for new versions and a button to try again.

**Comment by 0o-de-lally** [comment]
Implemented in 0.2.0
