### ISSUE TITLE
[Feature Request] Show Carpe version installed

### ISSUE THREAD

**Issue by soaresa** [0LNetworkCommunity/carpe#41]
# 🚀 Feature Request

## Motivation

We are about to have daily releases and it will be necessary for help-desk to know user Carpe version installed.

Soon we will have several issues being solved every week and to understand the problem user is facing it is necessary to know the version of Carpe installed on his machine.

## Pitch

**Describe the solution you'd like**
We should show Carpe version on footer with a link to "About" view which tells the commit hash, branch and tag name.

Something like this:
![image](https://user-images.githubusercontent.com/10797037/143588400-3c245960-f3cf-4e69-91ca-2a0deb75c5f4.png)

**Comment by liangping** [comment]
Hi. I have submitted a module in where front-end developers can get current commit hash, branch. package name, package version by calling `version::version ()` but tags was not able to get. 

Therefore. I think that we have to manually update version in Cargo.toml. make sure it's as same as tag.

**Comment by soaresa** [comment]
Hi Ping! I have moved the module to the "commands" folder.

For now we will update release version on Cargo.toml and tauri.conf.json files manually.

**Comment by soaresa** [comment]
Added on [v0.1.0](https://github.com/OLSF/carpe/releases/tag/v0.1.0)
