### ISSUE TITLE
Onboarding UX Issues

### ISSUE THREAD

**Issue by 0o-de-lally** [0LNetworkCommunity/carpe#5]
Miner first proof:

- [x] someone starts mining, and the miner displays account Bob, but it started mining on Alice's account (the profile it was switched to). This is a UX issue where the account switcher wasn't showing the correct account.

- [x] Miner should show how many proofs are in the users vdf_proof directory. Otherwise they may think there's nothing done. Or worse: lose their proof time to a different account (as above here).

- [ ] If there are proofs in the user's directory, but no info on chain, there should be a warning card, and give the user an opportunity to fix by sending the genesis/proof zero again.

- [ ] when a proof fails we need to keep the error message visible on the Miner app. The notification is too short. And the user shouldn't need to go into Debug mode.

- [x] miner could show CPU usage, or at least an icon showing that something is happening.

Onboard: 

- [x] when the app starts and there are no profiles created, it should only show the Newbie view (no nav menu - people get confused about what to do)

- [x] the miner nav and transactions option, should only appear if the account selected is already onboarded on chain. People get confused, they start mining before its ready

- [x] The Wallet page, should write very visibly when an account is not yet onboarded and give the instructions about what to do. This is hidden in the onboard modal.  Done: https://github.com/OLSF/carpe/pull/3

- [x] copy/paste from key shortcuts doesnt work on Mac, because there is no window menu created. Done: https://github.com/OLSF/carpe/pull/3

User Debugging:

- [x] switching between mainnet and testnet should only be an option in the Debug window.

- [x] debug window has layout issues, not critical for end users, but they may peek in there and it's ugly.

**Comment by JarrydTrokis** [comment]
I'm taking a look through the user debugging issues now

**Comment by 0o-de-lally** [comment]
deprecated
