### ISSUE TITLE
Message: "account does not yet exist on chain" shown for account which exists

### ISSUE THREAD

**Issue by mortonbits** [0LNetworkCommunity/carpe#7]
I observed the following behaviour on MAINNET:

1. Created new account in carpe
2. confirmed the account via command line: txs create-account .....
3. wallet tab displays the blue message box, saying that the account does not exist, even if balance is already shown obove. The box stays there even after restart of carpe:

![grafik](https://user-images.githubusercontent.com/82731659/141533061-99b282c7-d8ea-4085-946d-a101009c326d.png)

**Comment by soaresa** [comment]
I have fixed this issue and tested on my environment. It will come on my next PR.
