### ISSUE TITLE
Could we have Linux App Compile instructions please?

### ISSUE THREAD

**Issue by WyattLiu** [0LNetworkCommunity/carpe#9]
I am trying to compile carpe-vcarpe-0.0.1.3 using the tar.gz. However, I got stuck at 

   Compiling app v0.1.0 (/home/wyatt/carpe-vcarpe-0.0.1.3/src-tauri)
   Compiling diem-workspace-hack v0.1.0 (https://github.com/olsf/libra.git?branch=tauri#d9e487ec)
   Compiling gtk-sys v0.14.0
   Compiling gdk v0.14.3
   Compiling gtk v0.14.3
   Compiling webkit2gtk-sys v0.14.0
   Compiling rfd v0.4.4
   Compiling tauri-macros v1.0.0-beta.5
error: the option `Z` is only accepted on the nightly compiler

error: could not compile `app`

It looks like the cargo compile was just for getting an App for Mac, may I ask if there is a way to participate on Ubuntu?

Regards

**Comment by 0o-de-lally** [comment]
@soaresa for you I think.

**Comment by soaresa** [comment]
@WyattLiu , I am using Ubuntu to develop Carpe. Please let me know if you still have problems with the current Carpe version. Now you can reach out our dev channel at Discord now https://discord.com/channels/833074824447655976/833076424075902988
